add_newline = true

[character]
success_symbol = "[\\$](bright-green)"
error_symbol = "[\\$](bright-red)"

[line_break]
disabled = true

[cmd_duration]
min_time = 5_000
format = "⏱  [$duration]($style)"
style = "bright-blue"
disabled = true

[aws]
symbol = "  "
disabled = true

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
stashed = ""

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
style = "green"
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
